/*
 * generated by Xtext 2.29.0
 */
package es.um.uschema.xtext.skiql.serializer;

import com.google.inject.Inject;
import es.um.uschema.xtext.skiql.services.SkiqlGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class SkiqlSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SkiqlGrammarAccess grammarAccess;
	protected AbstractElementAlias match_NestedRelationshipQuery_FROMKeyword_2_q;
	protected AbstractElementAlias match_ReferenceVariationFilter_LeftSquareBracketRightSquareBracketKeyword_1_0_or___LeftSquareBracketKeyword_1_1_0_RightSquareBracketKeyword_1_1_2__;
	protected AbstractElementAlias match_VariationFilter_LeftSquareBracketRightSquareBracketKeyword_1_0_or___LeftSquareBracketKeyword_1_1_0_RightSquareBracketKeyword_1_1_2__;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SkiqlGrammarAccess) access;
		match_NestedRelationshipQuery_FROMKeyword_2_q = new TokenAlias(false, true, grammarAccess.getNestedRelationshipQueryAccess().getFROMKeyword_2());
		match_ReferenceVariationFilter_LeftSquareBracketRightSquareBracketKeyword_1_0_or___LeftSquareBracketKeyword_1_1_0_RightSquareBracketKeyword_1_1_2__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getReferenceVariationFilterAccess().getLeftSquareBracketKeyword_1_1_0()), new TokenAlias(false, false, grammarAccess.getReferenceVariationFilterAccess().getRightSquareBracketKeyword_1_1_2())), new TokenAlias(false, false, grammarAccess.getReferenceVariationFilterAccess().getLeftSquareBracketRightSquareBracketKeyword_1_0()));
		match_VariationFilter_LeftSquareBracketRightSquareBracketKeyword_1_0_or___LeftSquareBracketKeyword_1_1_0_RightSquareBracketKeyword_1_1_2__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getVariationFilterAccess().getLeftSquareBracketKeyword_1_1_0()), new TokenAlias(false, false, grammarAccess.getVariationFilterAccess().getRightSquareBracketKeyword_1_1_2())), new TokenAlias(false, false, grammarAccess.getVariationFilterAccess().getLeftSquareBracketRightSquareBracketKeyword_1_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_NestedRelationshipQuery_FROMKeyword_2_q.equals(syntax))
				emit_NestedRelationshipQuery_FROMKeyword_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ReferenceVariationFilter_LeftSquareBracketRightSquareBracketKeyword_1_0_or___LeftSquareBracketKeyword_1_1_0_RightSquareBracketKeyword_1_1_2__.equals(syntax))
				emit_ReferenceVariationFilter_LeftSquareBracketRightSquareBracketKeyword_1_0_or___LeftSquareBracketKeyword_1_1_0_RightSquareBracketKeyword_1_1_2__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VariationFilter_LeftSquareBracketRightSquareBracketKeyword_1_0_or___LeftSquareBracketKeyword_1_1_0_RightSquareBracketKeyword_1_1_2__.equals(syntax))
				emit_VariationFilter_LeftSquareBracketRightSquareBracketKeyword_1_0_or___LeftSquareBracketKeyword_1_1_0_RightSquareBracketKeyword_1_1_2__(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'FROM'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '{' (ambiguity) from=ReferenceEntitySpec
	 
	 * </pre>
	 */
	protected void emit_NestedRelationshipQuery_FROMKeyword_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '[]' | ('[' ']')
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 
	 * </pre>
	 */
	protected void emit_ReferenceVariationFilter_LeftSquareBracketRightSquareBracketKeyword_1_0_or___LeftSquareBracketKeyword_1_1_0_RightSquareBracketKeyword_1_1_2__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '[]' | ('[' ']')
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 
	 * </pre>
	 */
	protected void emit_VariationFilter_LeftSquareBracketRightSquareBracketKeyword_1_0_or___LeftSquareBracketKeyword_1_1_0_RightSquareBracketKeyword_1_1_2__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
