/*
 * generated by Xtext 2.29.0
 */
package es.um.uschema.xtext.skiql.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import es.um.uschema.xtext.skiql.SkiqlRuntimeModule;
import es.um.uschema.xtext.skiql.SkiqlStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SkiqlIdeSetup extends SkiqlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SkiqlRuntimeModule(), new SkiqlIdeModule()));
	}
	
}
