/*
 * generated by Xtext 2.25.0
 */
package es.um.uschema.xtext.athena.ide

import es.um.uschema.xtext.athena.ide.AbstractAthenaIdeModule

/**
 * Use this class to register ide components.
 */
class AthenaIdeModule extends AbstractAthenaIdeModule {
}
