/*
 * generated by Xtext 2.29.0
 */
package es.um.uschema.xtext.skiql.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SkiqlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("es/um/uschema/xtext/skiql/parser/antlr/internal/InternalSkiql.tokens");
	}
}
