/*
 * generated by Xtext 2.29.0
 */
package es.um.uschema.xtext.skiql.parser.antlr;

import com.google.inject.Inject;
import es.um.uschema.xtext.skiql.parser.antlr.internal.InternalSkiqlParser;
import es.um.uschema.xtext.skiql.services.SkiqlGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SkiqlParser extends AbstractAntlrParser {

	@Inject
	private SkiqlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSkiqlParser createParser(XtextTokenStream stream) {
		return new InternalSkiqlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SkiQLModel";
	}

	public SkiqlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SkiqlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
