/*
 * generated by Xtext 2.29.0
 */
package es.um.uschema.xtext.skiql.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class SkiqlWebModule extends AbstractSkiqlWebModule {
}
