/*
 * generated by Xtext 2.29.0
 */
package es.um.uschema.xtext.skiql.web;

import com.google.inject.Injector;

import es.um.uschema.xtext.skiql.SkiQLPackage;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.util.DisposableRegistry;
import org.eclipse.xtext.web.servlet.XtextServlet;

/**
 * Deploy this class into a servlet container to enable DSL-specific services.
 */
@WebServlet(name = "XtextServices", urlPatterns = "/xtext-service/*")
public class SkiqlServlet extends XtextServlet {
	
	private static final long serialVersionUID = 1L;
	
	DisposableRegistry disposableRegistry;
	
	public void init() throws ServletException {
		super.init();
		Injector injector = new SkiqlWebSetup().createInjectorAndDoEMFRegistration();
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("skiql", SkiQLPackage.eINSTANCE);
		this.disposableRegistry = injector.getInstance(DisposableRegistry.class);
	}
	
	public void destroy() {
		if (disposableRegistry != null) {
			disposableRegistry.dispose();
			disposableRegistry = null;
		}
		super.destroy();
	}
	
}
