/*
 * generated by Xtext 2.29.0
 */
package es.um.uschema.xtext.skiql.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import es.um.uschema.xtext.skiql.SkiqlRuntimeModule;
import es.um.uschema.xtext.skiql.SkiqlStandaloneSetup;
import es.um.uschema.xtext.skiql.ide.SkiqlIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class SkiqlWebSetup extends SkiqlStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SkiqlRuntimeModule(), new SkiqlIdeModule(), new SkiqlWebModule()));
	}
	
}
