/*
 * generated by Xtext 2.29.0
 */
package es.um.uschema.xtext.skiql;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SkiqlRuntimeModule extends AbstractSkiqlRuntimeModule {
}
