/*
 * generated by Xtext 2.29.0
 */
package es.um.uschema.xtext.skiql;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SkiqlStandaloneSetup extends SkiqlStandaloneSetupGenerated {

	public static void doSetup() {
		new SkiqlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
