/*
 * generated by Xtext 2.29.0
 */
package es.um.uschema.xtext.skiql.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link SkiqlWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractSkiqlWebModule extends DefaultWebModule {

}
