/*
 * generated by Xtext 2.29.0
 */
package es.um.uschema.xtext.skiql.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class SkiqlScopeProvider extends AbstractSkiqlScopeProvider {

}
