/*
 * generated by Xtext 2.29.0
 */
package es.um.uschema.xtext.skiql.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSkiqlScopeProvider extends DelegatingScopeProvider {
}
