package es.um.uschema.xtext.orion.m2m;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.nio.file.Path;

import org.junit.jupiter.api.Test;

import es.um.uschema.xtext.athena.athena.AthenaSchema;
import es.um.uschema.xtext.athena.utils.io.AthenaIO;
import es.um.uschema.xtext.orion.utils.io.OrionIO;
import es.um.uschema.xtext.orion.orion.OrionOperations;

class RelationshipOpTest
{
  private Path testPath_1 = Path.of("models/tests/m2m/relationship_ops/ImportRelationship_Ops.orion");
  private Path testPath_2 = Path.of("models/tests/m2m/relationship_ops/ScriptRelationship_Ops.orion");
  private OrionIO orionIO       = new OrionIO();
  private AthenaIO athenaIO     = new AthenaIO();

  @Test
  void testRelationshipOperations_Import()
  {
    OrionOperations orion = orionIO.load(testPath_1);
    AthenaSchema schema = new Orion2Athena().m2m(orion, false).get(0);

    assertEquals("Schema RelationshipSchema:2\r\n"
        + "\r\n"
        + "root entity EntityReferences\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  ref1: ref<EntityReferenced as String>+,\r\n"
        + "  ref2: ref<EntityReferenced feat Relationship1>+,\r\n"
        + "  ref3: ref<EntityReferenced feat Relationship2.1>+,\r\n"
        + "  ref4: ref<EntityReferenced feat Relationship2.1 , Relationship2.2>+,\r\n"
        + "  ref5: ref<EntityReferenced feat Ref5>+\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityReferenced\r\n"
        + "{\r\n"
        + "  +id: Identifier\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipToAdd_1\r\n"
        + "{\r\n"
        + "  key: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipToRename_1\r\n"
        + "{\r\n"
        + "  key: String,\r\n"
        + "  attr1: Number\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipRenamed_1\r\n"
        + "{\r\n"
        + "  key: String,\r\n"
        + "  attr3: Boolean\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipRenamed_2\r\n"
        + "{\r\n"
        + "  key: String,\r\n"
        + "  attr2: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipToExtract_1\r\n"
        + "{\r\n"
        + "  attr1: Number,\r\n"
        + "  attr2: String,\r\n"
        + "  attr3: List<Option < String , Boolean >>\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipToExtract_2\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    attr1: Number\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    attr2: String\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    attr3: List<Option < String , Boolean >>\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipToDelVar_1\r\n"
        + "{\r\n"
        + "  attr1: Number\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipToDelVar_2\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    attr: Number\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    attr1: String\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    attr3: List<Option < String , Boolean >>\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipToAdapt_1\r\n"
        + "{\r\n"
        + "  attr1: Number\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipToAdapt_2\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    attr: Number\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    attr1: String\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    attr3: List<Option < String , Boolean >>\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipToUnion_1\r\n"
        + "{\r\n"
        + "  attr1: Number\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship Relationship1\r\n"
        + "{\r\n"
        + "  attr1,\r\n"
        + "  attr2\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship Relationship2\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    attr\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    attr1\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    attr2\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipToAdd_2\r\n"
        + "{\r\n"
        + "  attr: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipExtracted_1\r\n"
        + "{\r\n"
        + "  attr1: Number,\r\n"
        + "  attr3: List<Option < String , Boolean >>\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipExtracted_2\r\n"
        + "{\r\n"
        + "  attr1: Number,\r\n"
        + "  ?attr3: List<Option < String , Boolean >>\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipSplit11\r\n"
        + "{\r\n"
        + "  attr1: Number,\r\n"
        + "  attr3: List<Option < String , Boolean >>\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipSplit12\r\n"
        + "{\r\n"
        + "  attr1: Number,\r\n"
        + "  attr2: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipSplit21\r\n"
        + "{\r\n"
        + "  attr1: Number,\r\n"
        + "  ?attr3: List<Option < String , Boolean >>\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipSplit22\r\n"
        + "{\r\n"
        + "  attr1: Number,\r\n"
        + "  ?attr2: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipMerged\r\n"
        + "{\r\n"
        + "  +key: String,\r\n"
        + "  attr1: List<Option < String , Boolean >>,\r\n"
        + "  attr2: Number,\r\n"
        + "  ?attr3: String,\r\n"
        + "  ?attr4: List<Option < String , Boolean >>\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipToUnion_2\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    attr: Number,\r\n"
        + "    attr1: String,\r\n"
        + "    attr2: Boolean,\r\n"
        + "    attr3: List<Option < String , Boolean >>\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship Ref5\r\n"
        + "{\r\n"
        + "  attr1,\r\n"
        + "  attr2,\r\n"
        + "  attr3\r\n"
        + "}\r\n", athenaIO.serialize(schema));
  }

  @Test
  void testRelationshipOperations_Script()
  {
    OrionOperations orion = orionIO.load(testPath_2);
    AthenaSchema schema = new Orion2Athena().m2m(orion).get(0);

    assertEquals("Schema ScriptRelationship_Ops:1\r\n"
        + "\r\n"
        + "relationship RelationshipAdded1\r\n"
        + "{\r\n"
        + "  id: Identifier\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipRenamed\r\n"
        + "{\r\n"
        + "  id: Identifier\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipSplit1\r\n"
        + "{\r\n"
        + "  attr1: String,\r\n"
        + "  attr2: String,\r\n"
        + "  attr3: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipSplit2\r\n"
        + "{\r\n"
        + "  attr1: String,\r\n"
        + "  attr5: String,\r\n"
        + "  attr6: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipMerged\r\n"
        + "{\r\n"
        + "  +id: String,\r\n"
        + "  a: String,\r\n"
        + "  b: Number,\r\n"
        + "  c: List\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipToExtract\r\n"
        + "{\r\n"
        + "  feat1,\r\n"
        + "  feat2,\r\n"
        + "  feat3,\r\n"
        + "  feat4\r\n"
        + "}\r\n"
        + "\r\n"
        + "relationship RelationshipExtracted\r\n"
        + "{\r\n"
        + "  feat2,\r\n"
        + "  feat4\r\n"
        + "}\r\n", athenaIO.serialize(schema));
  }
}
