/*
 * generated by Xtext 2.21.0
 */
package es.um.uschema.xtext.athena.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class AthenaValidator extends AbstractAthenaValidator {}
